[package]
name = "search-index"
version = "0.1.0-alpha.7"
authors = ["Markus Wiegand <mail@morphy2k.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tantivy = "0.16"
serde = { version="1", features=["derive"] }
tarkov-database-rs = { git="https://github.com/tarkov-database/tarkov-database-rs.git", tag="v0.1.0-alpha.13" }
thiserror = "1"
