[package]
name = "search-index"
version = "0.2.0-alpha.2"
authors = ["Markus Wiegand <mail@morphy2k.dev>"]
edition = "2021"
rust-version = "1.57"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tarkov-database-rs = { git = "https://github.com/tarkov-database/tarkov-database-rs.git", tag = "v0.2.0-alpha.6" }

tantivy = "0.17"
serde = { version = "1", features = ["derive"] }
thiserror = "1"
