[package]
name = "search-rest"
version = "0.1.0"
authors = ["Markus Wiegand <mail@morphy2k.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["jemalloc"]
jemalloc = ["jemallocator"]

[dependencies]
search-index = { path = "../search-index" }
jemallocator = { version = "0.3", optional = true }
serde = { version = "1", features = ["derive"] }
actix-web = "^3.0.0-beta"
regex = "1"
err-derive = "0.2"
env_logger = "0.7"
