[package]
name = "search-rest"
version = "0.1.0-alpha.3"
authors = ["Markus Wiegand <mail@morphy2k.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["jemalloc", "openssl"]

openssl = ["search-state/openssl"]
jemalloc = ["jemallocator"]

[dependencies]
search-index = { path = "../search-index" }
search-state = { path = "../search-state" }
jemallocator = { version = "0.3", optional = true }
serde = { version = "1", features = ["derive"] }
actix-web = "3.0.0-beta.3"
actix = "0.10.0-alpha.3"
log = "0.4"
err-derive = "0.2"
env_logger = "0.7"
