[package]
name = "search-rest"
version = "0.1.0-alpha.14"
authors = ["Markus Wiegand <mail@morphy2k.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["jemalloc", "openssl"]

openssl = ["search-state/openssl"]
jemalloc = ["jemallocator"]

[dependencies]
search-index = { path = "../search-index" }
search-state = { path = "../search-state" }
jemallocator = { version = "0.3", optional = true }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
humantime-serde = "1"
actix-web = "4.0.0-beta.6"
actix = "0.11"
tokio = "1"
futures-util = "0.3"
thiserror = "1"
log = "0.4"
env_logger = "0.8"
chrono = "0.4"
mime = "0.3"
tarkov-database-rs = { git = "https://github.com/tarkov-database/tarkov-database-rs.git", tag = "v0.1.0-alpha.12" }
jsonwebtoken = "7"
