name: Lint & Test

on:
  push:
    paths:
      - '**.rs'
      - '**/Cargo.lock'
      - '**/Cargo.toml'
      - '.github/workflows/lint-test.yaml'
    pull_request:
      types: [opened, edited, synchronize, reopened]
      paths:
        - '**.rs'
        - '**/Cargo.lock'
        - '**/Cargo.toml'

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:

    - name: Check out
      uses: actions/checkout@v3

    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          components: clippy, rustfmt
          override: true

    - uses: actions/cache@v3.0.1
      env:
        cache-name: lint
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: cargo-${{ env.cache-name }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          cargo-${{ env.cache-name }}
          cargo-

    - name: Run Clippy
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-features

    - name: Run Rustfmt
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: -- --check

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Check out
      uses: actions/checkout@v3

    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true

    - uses: actions/cache@v3.0.1
      env:
        cache-name: test
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: cargo-${{ env.cache-name }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          cargo-${{ env.cache-name }}
          cargo-

    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
